# Development Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icastar_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

# Development Server Configuration
server:
  port: 8080

# Development Logging
logging:
  level:
    com.icastar: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development-specific settings
icastar:
  file:
    upload-dir: uploads/dev/
  otp:
    expiration-minutes: 10  # Longer expiration for dev
    length: 4  # Shorter OTP for dev

# Development Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints in dev
  endpoint:
    health:
      show-details: always

# Development SpringDoc
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
    display-request-duration: true
