# QA Environment Configuration
spring:
  datasource:
    url: jdbc:mysql://qa-mysql-server:3306/icastar_qa?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME:qa_user}
    password: ${DB_PASSWORD:qa_password}
  
  jpa:
    hibernate:
      ddl-auto: validate  # Validate schema in QA
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# QA Server Configuration
server:
  port: 8080

# QA Logging
logging:
  level:
    com.icastar: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/icastar-qa.log

# QA-specific settings
icastar:
  file:
    upload-dir: uploads/qa/
  otp:
    expiration-minutes: 5
    length: 6
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET:icastar-qa-uploads}
      region: ${AWS_REGION:us-east-1}

# QA Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# QA SpringDoc
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
    display-request-duration: true

# QA Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# QA JWT Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:qa-jwt-secret-key-for-testing-environment-2024-this-is-a-very-long-secret-key-that-meets-the-512-bit-requirement-for-hs512-algorithm}
      expiration: 43200000  # 12 hours for QA
