server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  security:
    jwt:
      secret: test-secret-key-for-jwt-token-generation
      expiration: 86400000

logging:
  level:
    com.icastar: WARN
    org.springframework.security: WARN
